package jchunk.chunker.core.chunk;

/**
 * The Chunk record represents a segment of content with an associated identifier and
 * embedding. This record is used to store information about each chunk generated by the
 * IChunker implementation.
 *
 * @param id the unique identifier for the chunk
 * @param content the actual content of the chunk
 * @author Pablo Sanchidrian Herrera
 */
public record Chunk(Integer id, String content) {
}
