package jchunk.chunker.core.chunk;

/**
 * The Chunk record represents a segment of content with an associated identifier and
 * embedding. This record is used to store information about each chunk generated by the
 * IChunker implementation.
 *
 * @param id the unique identifier for the chunk
 * @param content the actual content of the chunk
 * @author Pablo Sanchidrian Herrera
 */
public record Chunk(Integer id, String content) {

	public static Builder builder() {
		return new Builder();
	}

	public static class Builder {

		private Integer id;

		private String content;

		public Builder id(Integer id) {
			this.id = id;
			return this;
		}

		public Builder content(String content) {
			this.content = content;
			return this;
		}

		public Chunk build() {
			return new Chunk(id, content);
		}

	}
}
