name: Maven Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures full Git history for Maven release plugin

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Configure Git with Token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.RELEASE_TOKEN }}@github.com/PabloSanchi/jchunk.git

      - name: Run Maven Release
        run: |
          mvn release:prepare -B
          mvn release:perform -B
